name: Create Archive
on:
  push:
    tags:
      - '*' # Trigger on tag pushes that start with 'v'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Prepare MuSkeMo Directory
      run: |
        mkdir -p MuSkeMo
        cp -r __init__.py scripts README.md "MuSkeMo utilities" MuSkeMo/ 
        cp "MuSkeMo manual/MuSkeMo manual.pdf" /  # Only copy the PDF
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'MuSkeMo.zip'
        path: 'MuSkeMo'
        exclusions: '*.git* /*node_modules/* .editorconfig citation.cff'
    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "MuSkeMo.zip"
        token: ${{ secrets.PAT_TOKEN }}  #for this to work, you must set "PAT_TOKEN" as a repository secret, under "actions".
        #when pushing commits from VSCode, you also need to set the following: git remote set-url origin https://[PASTE PAT HERE]@github.com/PashavanBijlert/MuSkeMo.git
        #The PAT also needs repo privileges and action/workflow privileges
